// Phase v2.0 MODELS-A-5f: model page (/models/:slug + /en/models/:slug).
// Sibling to BlogPostPage.tsx; same visual language (SiteHeader variant="page",
// breadcrumb, type badge, h1, meta line, FaqBlock), different semantics —
// TechArticle + SoftwareApplication, not BlogPosting. JSON-LD emitted by
// scripts/seo-routes.ts:buildModelRoute() mirrors the visible DOM.
//
// Graceful degradation: if content is undefined (model not yet generated by
// Phase 2 agents), shows only QuickFacts + InstallCta — page is still useful
// while content is incoming.

import { useParams } from "react-router";
import { useT, useLang } from "../../i18n/LangContext";
import LocalizedLink from "../components/LocalizedLink";
import SiteHeader from "../components/SiteHeader";
import SiteFooter from "../components/SiteFooter";
import FaqBlock from "../components/FaqBlock";
import ModelQuickFacts from "../components/ModelQuickFacts";
import InlineOptenCallout from "../components/InlineOptenCallout";
import ModelInstallCta from "../components/ModelInstallCta";
import RelatedModels from "../components/RelatedModels";
import { getModelBySlug } from "../../content/models";
import { metaField } from "../../content/models/metaEn";

function formatDate(iso: string, lang: "ru" | "en"): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  const locale = lang === "ru" ? "ru-RU" : "en-US";
  return d.toLocaleDateString(locale, { year: "numeric", month: "long", day: "numeric" });
}

function NotFoundFallback() {
  const t = useT();
  return (
    <div className="min-h-screen bg-[#011417] font-['PT_Root_UI',sans-serif] flex flex-col items-center justify-center px-[20px]">
      <h1 className="text-white text-[28px] md:text-[32px] font-medium mb-[12px]">
        {t("models.notFound.title")}
      </h1>
      <p className="text-[rgba(255,255,255,0.6)] text-[16px] mb-[24px]">
        {t("models.notFound.body")}
      </p>
      <LocalizedLink
        to="/models"
        className="rounded-[100px] bg-white px-[24px] py-[12px] text-[#011417] text-[14px] font-bold no-underline"
      >
        {t("models.notFound.cta")}
      </LocalizedLink>
    </div>
  );
}

export default function ModelPage() {
  const { slug } = useParams<{ slug: string }>();
  const { lang } = useLang();
  const t = useT();

  const entry = slug ? getModelBySlug(slug) : undefined;
  if (!entry) {
    return <NotFoundFallback />;
  }

  const { meta, content } = entry;
  const locale = content?.[lang];
  const typeLabel = meta.type === "video"
    ? t("models.quickFacts.typeVideo")
    : t("models.quickFacts.typeImage");

  // Fallback heading + intro when content is not generated yet (Phase 1 stub).
  const localizedName = metaField(meta, "name", lang) ?? meta.name;
  const heading = locale?.h1 ?? `${localizedName}: ${typeLabel.toLowerCase()}`;
  const intro = locale?.intro ?? "";

  return (
    <div className="min-h-screen bg-[#011417] font-['PT_Root_UI',sans-serif] text-white">
      <SiteHeader variant="page" />

      <main className="mx-auto max-w-[800px] px-[20px] pb-[60px] pt-[120px] sm:pt-[140px]">
        {/* Breadcrumb (visible mirror of JSON-LD BreadcrumbList) */}
        <nav
          aria-label="Breadcrumb"
          className="mb-[24px] flex flex-wrap items-center gap-x-[8px] gap-y-[4px] text-[13px] text-white/45"
        >
          <LocalizedLink to="/" className="no-underline text-inherit transition hover:text-white">
            {t("nav.home")}
          </LocalizedLink>
          <span aria-hidden="true">/</span>
          <LocalizedLink to="/models" className="no-underline text-inherit transition hover:text-white">
            {t("nav.models")}
          </LocalizedLink>
          <span aria-hidden="true">/</span>
          <span aria-current="page" className="max-w-full truncate text-white/75">{localizedName}</span>
        </nav>

        {/* Type badge */}
        <span className="inline-flex w-fit items-center rounded-full bg-[rgba(156,251,81,0.15)] px-[10px] py-[3px] text-[11px] font-bold uppercase tracking-[1px] text-[#9cfb51]">
          {typeLabel}
        </span>

        <h1 className="mt-[16px] font-['Unbounded',sans-serif] text-[28px] font-medium leading-[1.15] tracking-[-0.6px] text-white md:text-[40px]">
          {heading}
        </h1>

        {/* Meta line */}
        <p className="mt-[16px] text-[14px] leading-[1.55] text-white/45">
          <span className="text-white/70">{meta.vendor}</span>
          {" · "}
          {t("models.updatedLabel")}: <time dateTime={meta.updatedAt}>{formatDate(meta.updatedAt, lang)}</time>
        </p>

        {/* Definitional intro — 40-60 words, speakable-eligible. Hidden when stub. */}
        {intro && (
          <p className="model-intro mt-[28px] text-[17px] leading-[1.6] text-white/75 md:text-[18px]">
            {intro}
          </p>
        )}

        {/* Quick-Facts table — always shown (works even without content) */}
        <ModelQuickFacts meta={meta} />

        {/* Section 1 — "Что умеет" */}
        {locale && locale.sections[0] && (
          <section className="mt-[24px] border-t border-white/10 pt-[24px]">
            <h2 className="mb-[12px] text-[22px] font-medium leading-[1.3] tracking-[-0.4px] text-white md:text-[24px]">
              {locale.sections[0].heading}
            </h2>
            {locale.sections[0].body.split("\n\n").map((p, i) => (
              <p key={i} className="mb-[14px] text-[16px] leading-[1.7] text-white/78">{p}</p>
            ))}
            {locale.sections[0].bullets && locale.sections[0].bullets.length > 0 && (
              <ul className="mt-[12px] list-disc pl-[20px] text-[16px] leading-[1.7] text-white/78">
                {locale.sections[0].bullets.map((b, i) => (
                  <li key={i} className="mb-[6px]">{b}</li>
                ))}
              </ul>
            )}
          </section>
        )}

        {/* Inline callout A — after features */}
        <InlineOptenCallout variant="after-features" meta={meta} />

        {/* Section 2 — "Структура промпта" + any extra prose sections (skip the
            last one — that goes under mistakes) */}
        {locale && locale.sections.slice(1, -1).map((sec, i) => (
          <section key={i} className="mt-[24px] border-t border-white/10 pt-[24px]">
            <h2 className="mb-[12px] text-[22px] font-medium leading-[1.3] tracking-[-0.4px] text-white md:text-[24px]">
              {sec.heading}
            </h2>
            {sec.body.split("\n\n").map((p, j) => (
              <p key={j} className="mb-[14px] text-[16px] leading-[1.7] text-white/78">{p}</p>
            ))}
            {sec.bullets && sec.bullets.length > 0 && (
              <ul className="mt-[12px] list-disc pl-[20px] text-[16px] leading-[1.7] text-white/78">
                {sec.bullets.map((b, j) => (
                  <li key={j} className="mb-[6px]">{b}</li>
                ))}
              </ul>
            )}
            {sec.table && sec.table.rows.length > 0 && (
              <table className="mt-[16px] w-full border-collapse text-[14px]">
                <tbody>
                  {sec.table.rows.map(([k, v], j) => (
                    <tr key={j} className="border-t border-white/10">
                      <td className="py-[8px] pr-[12px] text-white/55">{k}</td>
                      <td className="py-[8px] text-white/85">{v}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </section>
        ))}

        {/* Mistakes block */}
        {locale && locale.mistakes.length > 0 && (
          <section className="mt-[24px] border-t border-white/10 pt-[24px]">
            <h2 className="mb-[16px] text-[22px] font-medium leading-[1.3] tracking-[-0.4px] text-white md:text-[24px]">
              {t("models.mistakes.heading")}
            </h2>
            <ol className="flex flex-col gap-[16px]">
              {locale.mistakes.map((m, i) => (
                <li key={i} className="rounded-[8px] border border-[rgba(212,24,61,0.2)] bg-[rgba(212,24,61,0.06)] p-[14px]">
                  <h3 className="mb-[6px] text-[16px] font-medium text-white">
                    {i + 1}. {m.title}
                  </h3>
                  <p className="text-[15px] leading-[1.6] text-white/72">{m.explain}</p>
                </li>
              ))}
            </ol>
          </section>
        )}

        {/* Inline callout B — after mistakes */}
        <InlineOptenCallout variant="after-mistakes" meta={meta} />

        {/* Examples — before/after */}
        {locale && locale.examples.length > 0 && (
          <section className="mt-[24px] border-t border-white/10 pt-[24px]">
            <h2 className="mb-[16px] text-[22px] font-medium leading-[1.3] tracking-[-0.4px] text-white md:text-[24px]">
              {t("models.examples.heading")}
            </h2>
            <div className="flex flex-col gap-[20px]">
              {locale.examples.map((ex, i) => (
                <div key={i}>
                  <p className="mb-[8px] text-[12px] font-bold uppercase tracking-[1px] text-white/45">
                    {t("models.examples.example")} {i + 1}
                  </p>
                  <div className="grid gap-[12px] md:grid-cols-2">
                    <div className="rounded-[8px] border border-[rgba(212,24,61,0.2)] bg-[rgba(212,24,61,0.08)] p-[14px]">
                      <p className="mb-[6px] text-[11px] font-bold uppercase tracking-[1px] text-[#d4183d]">
                        {t("models.examples.beforeLabel")}
                      </p>
                      <pre className="whitespace-pre-wrap font-mono text-[13px] leading-[1.6] text-white/70">{ex.before}</pre>
                    </div>
                    <div className="rounded-[8px] border border-[rgba(156,251,81,0.2)] bg-[rgba(156,251,81,0.06)] p-[14px]">
                      <p className="mb-[6px] text-[11px] font-bold uppercase tracking-[1px] text-[#9cfb51]">
                        {t("models.examples.afterLabel")}
                      </p>
                      <pre className="whitespace-pre-wrap font-mono text-[13px] leading-[1.6] text-white/85">{ex.after}</pre>
                    </div>
                  </div>
                  {ex.note && (
                    <p className="mt-[8px] text-[13px] italic leading-[1.5] text-white/55">{ex.note}</p>
                  )}
                </div>
              ))}
            </div>
          </section>
        )}
      </main>

      {/* FAQ — FaqBlock id matches verify-faq-mainentity.mjs regex (id="[^"]*faq[^"]*") */}
      {locale && locale.faq.length > 0 && (
        <FaqBlock items={locale.faq} headingKey="models.faqHeading" id="model-faq" />
      )}

      {/* Related models */}
      <RelatedModels currentSlug={meta.slug} type={meta.type} />

      {/* Final install CTA */}
      <ModelInstallCta meta={meta} />

      <SiteFooter />
    </div>
  );
}
