// AUTO-GENERATED by scripts/generate-summaries.mjs — do not edit by hand.
// Lightweight per-model intro strings for the /models hub + RelatedModels cards.
// Full model content lives in <slug>.ts and ships per-page via the #opten-model
// data-island (Speed/Phase B), NOT in the client entry chunk.
// Rerun `node scripts/generate-summaries.mjs` after content changes.

export interface ModelSummary {
  ru: string;
  en: string;
}

export const MODEL_SUMMARIES: Record<string, ModelSummary> = {
  "flux": {
    "ru": "FLUX — семейство image-моделей от Black Forest Labs (schnell, dev, pro, 1.1 pro Ultra, FLUX.2, Kontext). Двойной энкодер CLIP + T5-XXL понимает длинные связные описания лучше большинства конкурентов. Оптимальная длина промпта — 50–200 слов на английском, структура — субъект, сцена, освещение, стиль, параметры камеры.",
    "en": "FLUX is a family of image models from Black Forest Labs (schnell, dev, pro, 1.1 pro Ultra, FLUX.2, Kontext). Its dual CLIP + T5-XXL text encoder understands long coherent descriptions better than most competitors. Optimal prompt length is 50–200 English words, structured as subject, scene, lighting, style, and camera parameters."
  },
  "flux-1": {
    "ru": "FLUX.1 — флагманская image-модель от Black Forest Labs (schnell, dev, pro, 1.1 pro Ultra). Двойной энкодер CLIP + T5-XXL интерпретирует длинные связные описания значительно точнее моделей на одном CLIP, рендерит текст в кадре на уровне лидеров рынка, поддерживает разрешения до 2752×2752 в Ultra-варианте.",
    "en": "FLUX.1 is Black Forest Labs' flagship image model (schnell, dev, pro, 1.1 pro Ultra). Its dual CLIP + T5-XXL encoder interprets long coherent descriptions significantly better than single-CLIP models, renders in-image text at top-tier level, and supports up to 2752×2752 in the Ultra variant."
  },
  "flux-kontext": {
    "ru": "FLUX Kontext — image-to-image модель редактирования от Black Forest Labs (Pro, Max, Multi). Принимает входное изображение плюс инструкцию по изменению. Главное отличие от обычных text-to-image моделей — Kontext видит исходник и не нужно переописывать всю сцену; промпт описывает только что изменить.",
    "en": "FLUX Kontext is Black Forest Labs' image-to-image editing model (Pro, Max, Multi). It accepts an input image plus a change instruction. The key difference from regular text-to-image models — Kontext sees the source and there's no need to redescribe the whole scene; the prompt describes only what to change."
  },
  "gpt-image": {
    "ru": "GPT Image — семейство image-моделей OpenAI (1, 1.5, 2). Понимает естественный язык, обрабатывает промпт как рассказ с визуальной конкретикой, поддерживает разрешения 1024×1024, 1536×1024 и 1024×1536, прозрачный фон и три уровня качества. Сильная сторона — рендеринг читаемого текста в кадре.",
    "en": "GPT Image is OpenAI's image model family (1, 1.5, 2). It understands natural language, treats prompts as stories with visual specifics, supports 1024×1024, 1536×1024, and 1024×1536 resolutions, transparent background, and three quality tiers. The standout feature is rendering readable in-image text."
  },
  "gpt-image-1": {
    "ru": "GPT Image 1 — image-модель от OpenAI с естественным языковым промптингом и сильным рендерингом текста в кадре. Работает через ChatGPT и API, поддерживает разрешения до 1536×1024, прозрачный фон, три уровня качества и image-to-image редактирование. Промпт длиной ~500 слов оптимален.",
    "en": "GPT Image 1 is an OpenAI image model with natural-language prompting and strong in-image text rendering. It runs in ChatGPT and via API, supports resolutions up to 1536×1024, transparent background, three quality tiers, and image-to-image editing. Prompts of ~500 words are optimal."
  },
  "gpt-image-1.5": {
    "ru": "GPT Image 1.5 — image-модель OpenAI с улучшенным фотореализмом, сохранением идентичности при редактировании и multi-image входом. Поддерживает разрешения до 1536×1024, прозрачный фон, три уровня качества, параметр input_fidelity (high/low) и до 4 изображений за запрос. Промпт оптимальной длины — до 500 слов.",
    "en": "GPT Image 1.5 is OpenAI's image model with improved photorealism, identity preservation during editing, and multi-image input. It supports resolutions up to 1536×1024, transparent background, three quality tiers, an input_fidelity parameter (high/low), and up to 4 images per request. Optimal prompt length is up to 500 words."
  },
  "gpt-image-2": {
    "ru": "GPT Image 2 — image-модель от OpenAI с SOTA-рендерингом текста и thinking mode. Понимает промпт как бриф для дизайнера, обрабатывает слова последовательно (первые слова весят больше) и поддерживает до 16 референсов и 8 связанных изображений за один запрос. Лучше всего работает с английским, но многоязычная поддержка стабильная.",
    "en": "GPT Image 2 is OpenAI's image model with SOTA in-image text rendering and a thinking mode. It treats prompts as design briefs, processes tokens sequentially (first words carry the most weight), and supports up to 16 reference images plus 8 linked outputs per request. English works best, but multilingual support is solid."
  },
  "grok-imagine": {
    "ru": "Grok Imagine (Aurora) — image-модель xAI с авторегрессивной MoE Transformer архитектурой, не diffusion. Сильна в фотореалистичных портретах и точном рендеринге текста. Поддерживает разрешение до 2K, промпты до 10000 символов, 14+ соотношений сторон и до 10 изображений за запрос. Негативные промпты не работают.",
    "en": "Grok Imagine (Aurora) is xAI's image model with an autoregressive MoE Transformer architecture, not diffusion. It excels at photorealistic portraits and accurate in-image text rendering. It supports up to 2K resolution, prompts up to 10,000 characters, 14+ aspect ratios, and up to 10 images per request. Negative prompts do not work."
  },
  "happy-horse": {
    "ru": "Happy Horse 1.0 (快乐小马) — video-модель от Alibaba ATH AI Innovation Unit, 15B параметров, unified single-stream Transformer. Генерирует 5–8 секунд 1080p за ~10 секунд на H100. Joint audio-video в одном forward pass, lip-sync на 7 языках, open source. Главное правило промптинга — brevity wins, ~20 слов на простой кадр.",
    "en": "Happy Horse 1.0 (快乐小马) is Alibaba ATH AI Innovation Unit's video model — 15B parameters, unified single-stream Transformer. It generates 5–8 seconds of 1080p in ~10 seconds on an H100. Joint audio-video in a single forward pass, lip-sync in 7 languages, open source. The core prompting rule — brevity wins, ~20 words for a simple shot."
  },
  "higgsfield": {
    "ru": "Higgsfield — платформа с проприетарными моделями Soul 2.0 (image, до 4K), Soul Cinema (era-aware image) и DoP (image-to-video, 5 секунд, 720–1080p, 100+ motion presets). Soul понимает субкультурные коды и микротренды нативно, DoP принимает короткие командные промпты — одно действие плюс одно движение камеры за раз.",
    "en": "Higgsfield is a platform with proprietary models — Soul 2.0 (image, up to 4K), Soul Cinema (era-aware image), and DoP (image-to-video, 5 seconds, 720–1080p, 100+ motion presets). Soul understands subcultural codes and micro-trends natively; DoP accepts short command-style prompts — one action plus one camera move at a time."
  },
  "imagen": {
    "ru": "Google Imagen — семейство image-моделей от Google, доступное через ImageFX, Vertex AI и Freepik. Понимает естественный язык лучше, чем списки тегов через запятую, оптимизировано под английский и поддерживает читаемый текст на изображениях. Негативный промпт не поддерживается — описывай, что нужно, а не то, чего быть не должно.",
    "en": "Google Imagen is Google's family of image models available through ImageFX, Vertex AI, and Freepik. It understands natural language better than comma-separated tag lists, is optimized for English, and supports legible in-image text. Negative prompts are not supported — describe what should be there, not what shouldn't."
  },
  "imagen-4": {
    "ru": "Imagen 4 — image-модель Google нового поколения с улучшенной типографикой и ультра-фотореализмом. Работает на естественном языке, оптимизирована под английский, поддерживает чёткий рендер текста с правильным кернингом. Идёт в трёх версиях — Fast, стандарт и Ultra; все используют единую структуру промптов и до 10× быстрее Imagen 3.",
    "en": "Imagen 4 is Google's next-generation image model with upgraded typography and ultra-photorealism. It works on natural language, is optimized for English, and supports crisp in-image text with proper kerning. It ships in three versions — Fast, standard, and Ultra; all share the same prompt structure and Fast is up to 10x quicker than Imagen 3."
  },
  "imagen-4-ultra": {
    "ru": "Imagen 4 Ultra — premium-версия Imagen 4 от Google с максимальной детализацией и верностью промпту. Раскрывается на длинных детальных описаниях (100–400 слов), реализует микро-текстуры (поры, нити, швы) и сложные многофигурные сцены. Лучший рендер текста в семействе и самая «послушная» модель Google для production-задач.",
    "en": "Imagen 4 Ultra is Google's premium Imagen 4 with maximum detail and prompt fidelity. It rewards long, detailed descriptions (100–400 words), renders micro-textures (pores, threads, stitches), and handles complex multi-figure scenes. It has the best text rendering in the family and is the most obedient Google model for production work."
  },
  "kling": {
    "ru": "Kling — семейство видеомоделей от Kuaishou, доступное через klingai.com. Генерирует видео до 10 секунд (до 15 секунд в Kling 3.0), поддерживает T2V, I2V и Motion Control. Промпт принимает до ~2500 символов, оптимальная длина 50–150 слов. Английский даёт самые стабильные результаты; есть поддержка негативного промпта.",
    "en": "Kling is Kuaishou's video model family, available at klingai.com. It generates up to 10-second clips (up to 15 seconds in Kling 3.0) and supports T2V, I2V, and Motion Control. Prompts accept up to ~2500 characters; the sweet spot is 50–150 words. English yields the most stable results, and a negative prompt field is supported."
  },
  "kling-2.6": {
    "ru": "Kling 2.6 Pro — видеомодель от Kuaishou, доступная на klingai.com. Генерирует клипы до 10 секунд в 1080p, поддерживает T2V, I2V, Elements (до 4 референсов) и Motion Control. Оптимальная длина промпта 50–150 слов, лучше всего работает с английским и принимает negative prompt как отдельное поле.",
    "en": "Kling 2.6 Pro is Kuaishou's video model on klingai.com. It generates clips up to 10 seconds at 1080p and supports T2V, I2V, Elements (up to 4 references), and Motion Control. Optimal prompt length is 50–150 words; it performs best in English and accepts a negative prompt as a separate field."
  },
  "kling-3": {
    "ru": "Kling 3.0 — флагманская видеомодель Kuaishou на klingai.com. Длительность до 15 секунд, Multi-shot до 6 шотов в одной генерации, нативная генерация диалогов и аудио с управлением тоном голоса, мультиязычные акценты и code-switching. Создана для понимания режиссёрского намерения, а не просто списка объектов.",
    "en": "Kling 3.0 is Kuaishou's flagship video model on klingai.com. Duration up to 15 seconds, Multi-shot with up to 6 shots in one generation, native dialogue and audio generation with voice-tone control, multilingual accents, and code-switching. Built to understand directorial intent, not just an object list."
  },
  "kling-motion-control": {
    "ru": "Kling Motion Control — режим Kling от Kuaishou для переноса движений с референсного видео на персонажа из изображения. Длительность 5–10 секунд, разрешение до 4K (Kling 3.0), Motion Brush до 6 элементов на кадр. Главное правило: промпт = арт-дирекция (как выглядит), а НЕ режиссура движения (как двигается).",
    "en": "Kling Motion Control is a Kuaishou Kling mode for transferring motion from a reference video onto a character from an image. Duration 5–10 seconds, resolution up to 4K (Kling 3.0), Motion Brush up to 6 elements per frame. The golden rule: the prompt is art direction (how it looks), NOT motion direction (how it moves)."
  },
  "kling-o1": {
    "ru": "Kling O1 — рассуждающая видеомодель Kuaishou на klingai.com. Длительность до 10 секунд, разрешение до 1080p, четыре специализированных режима: I2V, V2V Transform, Reference-to-Video и V2V Edit. Каждый режим требует своей стратегии промптинга — применение неправильной стратегии даёт нестабильные результаты, даже если промпт детальный.",
    "en": "Kling O1 is Kuaishou's reasoning video model on klingai.com. Duration up to 10 seconds, resolution up to 1080p, four specialized modes: I2V, V2V Transform, Reference-to-Video, and V2V Edit. Each mode needs its own prompting strategy — applying the wrong strategy gives unstable results, even with a detailed prompt."
  },
  "ltx-2": {
    "ru": "LTX 2 — open-source видеомодель от Lightricks на ltx.io. Существует в двух версиях: Fast (до 20 секунд, 2× быстрее) и Pro (до 10 секунд, плюс Audio-to-Video и Retake). Нативное 4K до 50 FPS, генерация аудио, Apache-лицензия. Промпт пишется как кинематографический shot list, оптимальная длина около 200 слов на английском.",
    "en": "LTX 2 is Lightricks' open-source video model at ltx.io. It comes in two versions: Fast (up to 20 seconds, 2x faster) and Pro (up to 10 seconds, plus Audio-to-Video and Retake). Native 4K up to 50 FPS, audio generation, Apache license. The prompt is written as a cinematographer's shot list — optimal length around 200 words in English."
  },
  "luma-ray": {
    "ru": "Luma Ray — общее семейство видеомоделей Luma в Dream Machine: Ray 1.x, Ray 2, Ray 3.14 и Ray 3 Reasoning. Все модели Ray работают по одной формуле — субъект + mid-action verb + сцена + вторичное движение + камера + свет. Это «positive-only» модели: негативные промпты контрпродуктивны. Длительность 5–10 секунд, extend до ~30 секунд.",
    "en": "Luma Ray is the Luma video-model family in Dream Machine: Ray 1.x, Ray 2, Ray 3.14, and Ray 3 Reasoning. All Ray models share the same formula — subject + mid-action verb + setting + secondary motion + camera + lighting. These are positive-only models: negative prompts are counter-productive. Duration is 5–10 seconds, extend up to 30 seconds."
  },
  "luma-ray-2": {
    "ru": "Luma Ray 2 — крупномасштабная видеомодель Luma в Dream Machine, обученная напрямую на видеоданных. Понимает естественное движение, реалистичное освещение и физически корректные взаимодействия. Длительность 5 или 10 секунд, нативное 720p и 1080p, апскейл до 4K. Главное улучшение от Ray 1.6 — устранена проблема slow-motion, нативный 10-секундный лимит, Camera Tags в интерфейсе.",
    "en": "Luma Ray 2 is Luma's large-scale video model in Dream Machine, trained directly on video data. It understands natural motion, realistic lighting, and physically correct interactions. Duration is 5 or 10 seconds, native 720p and 1080p with upscale to 4K. The main upgrade from Ray 1.6 — slow-motion is fixed, native 10-second limit, Camera Tags in the interface."
  },
  "luma-ray-3": {
    "ru": "Luma Ray 3 — линейка моделей Luma: Ray 3.14 (рабочая лошадка, default для 90% задач), Ray 3 Reasoning (мультимодальная «рассуждающая» модель). Доступна в Dream Machine и Adobe Firefly. Уникальные возможности: Character Reference для сохранения идентичности персонажа, Draft Mode (5–10x быстрее), 16-bit HDR, Visual Annotation, нативное 1080p. Длительность 5 или 10 секунд.",
    "en": "Luma Ray 3 is the Ray 3 lineup: Ray 3.14 (the workhorse, default for 90% of tasks) and Ray 3 Reasoning (the multimodal «thinking» model). Available in Dream Machine and Adobe Firefly. Unique features: Character Reference for character identity, Draft Mode (5–10x faster), 16-bit HDR, Visual Annotation, native 1080p. Duration is 5 or 10 seconds."
  },
  "luma-uni-1": {
    "ru": "Luma Uni-1 — image-модель Luma Labs с уникальной архитектурой: decoder-only autoregressive transformer (НЕ диффузия), генерирует пиксели последовательно. Нативное 2K разрешение, reasoning по умолчанию (модель «думает» о композиции перед рендером), до 9 референсов с явными ролями (CHARACTER, STYLE, LIGHTING и др.), сильная мультиязычность. Доступна через Luma Labs и REST API.",
    "en": "Luma Uni-1 is a Luma Labs image model with a unique architecture: decoder-only autoregressive transformer (NOT diffusion), generating pixels sequentially. Native 2K resolution, reasoning on by default (the model «thinks» about composition before rendering), up to 9 references with explicit roles (CHARACTER, STYLE, LIGHTING, etc.), strong multilingual support. Available via Luma Labs and REST API."
  },
  "midjourney": {
    "ru": "Midjourney — серия image-моделей от компании Midjourney, доступная через midjourney.com и Discord. Линейка включает V7 (основная), V8 Alpha (новая, web-only), Niji 6/7 (аниме). Все версии используют общий синтаксис параметров (--ar, --s, --sref) и иерархию промпта, но V7+ требуют естественного языка вместо списков тегов.",
    "en": "Midjourney is a family of image models from Midjourney Inc., available via midjourney.com and Discord. The lineup includes V7 (main), V8 Alpha (newest, web-only), Niji 6/7 (anime). All versions share the same parameter syntax (--ar, --s, --sref) and prompt hierarchy, but V7+ require natural language instead of tag lists."
  },
  "midjourney-7": {
    "ru": "Midjourney V7 — флагманская image-модель Midjourney с релиза 3 апреля 2025. V7 фундаментально изменила работу с промптами: теперь модель понимает естественный английский язык, а старый подход «keywords через запятую» активно ухудшает результат. Слова в начале промпта весят больше, лучший фотореализм в семействе, персонализация включена по умолчанию.",
    "en": "Midjourney V7 is Midjourney's flagship image model released on April 3, 2025. V7 fundamentally changed prompt writing — the model now understands natural English, and the old «keywords with commas» approach actively hurts results. Opening words carry more weight, photorealism is the best in the family, and personalization is enabled by default."
  },
  "midjourney-8": {
    "ru": "Midjourney V8 Alpha — новая модель, доступная с 17 марта 2026 только на alpha.midjourney.com (Discord не поддерживается). V8 — это не улучшенная V7, а другая модель с буквальной интерпретацией, нативным 2K через `--hd`, скоростью в 5 раз выше V7 и центральной ролью персонализации. Главное правило: указывай освещение явно, иначе результат будет плоским.",
    "en": "Midjourney V8 Alpha is the new model, available since March 17, 2026 only on alpha.midjourney.com (Discord is not supported). V8 is not an improved V7 — it's a different model with literal interpretation, native 2K via `--hd`, 5x faster generation, and personalization at the center. The headline rule: state lighting explicitly, otherwise the result will be flat."
  },
  "midjourney-8.1": {
    "ru": "Midjourney V8.1 Alpha — апгрейд V8, доступный только через alpha.midjourney.com (Discord не поддерживается). Главные сдвиги: HD теперь дефолт (флаг --hd не нужен), параметры `--no`, `--ow`, `--p 0` удалены, image-референсы загружаются только через UI-слоты. Модель ещё более буквальна, чем V8, и имеет сильный baked-in bokeh, требующий anti-bokeh stack для документального реализма.",
    "en": "Midjourney V8.1 Alpha is the V8 upgrade, available only on alpha.midjourney.com (no Discord). Main shifts: HD is now default (the --hd flag is gone), parameters `--no`, `--ow`, `--p 0` are removed, image references load only via UI slots. The model interprets even more literally than V8 and has strong baked-in bokeh that requires an anti-bokeh stack for documentary realism."
  },
  "midjourney-niji": {
    "ru": "Midjourney Niji — специализированная модель Midjourney для аниме, манги и восточной иллюстрации. Текущая рекомендуемая версия — Niji 7 (с 9 января 2026): чистые плоские линии, кристально чёткие глаза, лучший в семействе --sref с минимальным дрейфом стиля, поддержка персонализации. Niji 6 — legacy для случаев, когда нужны стилевые пресеты (--style expressive/cute/scenic) или --cref.",
    "en": "Midjourney Niji is the specialized Midjourney model for anime, manga, and Eastern illustration. The current recommended version is Niji 7 (released January 9, 2026): clean flat linework, crystal-clear eyes, the best --sref stability in the family with minimal style drift, personalization support. Niji 6 is legacy — used only when you need style presets (--style expressive/cute/scenic) or --cref."
  },
  "midjourney-video": {
    "ru": "Midjourney Video — Image-to-Video модель Midjourney для короткой анимации статичных изображений. Чистый Text-to-Video не поддерживается: референсное изображение обязательно. Промпт описывает что движется и как движется камера, а не внешность субъекта — это уже задано картинкой. Английский — основной язык, оптимальная длина 20-60 слов.",
    "en": "Midjourney Video is Midjourney's Image-to-Video model for short animations of still images. Pure Text-to-Video isn't supported: a reference image is mandatory. The prompt describes what moves and how the camera moves — not the subject's appearance, which is already set by the image. English is the primary language; optimal length 20-60 words."
  },
  "minimax-hailuo-02": {
    "ru": "MiniMax Hailuo 02 — предшественник Hailuo 2.3, до сих пор актуальный благодаря уникальному режиму FL2V (First-and-Last-Frame-to-Video) и сильной физике на экстремальных движениях вроде гимнастики и паркура. Промпт пишется как режиссёрские заметки, поддерживается bracket camera syntax `[Push in]`. Английский предпочтителен; оптимальная длина 40-60 слов.",
    "en": "MiniMax Hailuo 02 is the predecessor of Hailuo 2.3, still relevant for its unique FL2V (First-and-Last-Frame-to-Video) mode and strong physics on extreme motion. Prompts are written as director's notes; bracket camera syntax `[Push in]` is supported. English is preferred; optimal length 40-60 words."
  },
  "minimax-hailuo-2.3": {
    "ru": "MiniMax Hailuo 2.3 — флагман видеомоделей MiniMax: T2V и I2V до 1080P, 25fps, поддержка bracket camera syntax `[Push in]`. Промпт пишется как режиссёрские заметки на естественном языке, не теги. Английский рекомендован, китайский — родной язык обучения; оптимальная длина 40-60 слов.",
    "en": "MiniMax Hailuo 2.3 is the flagship of MiniMax video models: T2V and I2V up to 1080P, 25fps, with bracket camera syntax `[Push in]` support. Prompts are written as director's notes in natural language, not tags. English is recommended; Chinese is the native training language. Optimal length 40-60 words."
  },
  "minimax-live-illustrations": {
    "ru": "MiniMax I2V-01-Live — специализированная Image-to-Video модель для анимации 2D-иллюстраций: аниме, манги, цифровых портретов, концепт-арта и книжных иллюстраций. До 720P, длительность до 6 секунд. Модель сохраняет арт-стиль и линии оригинала и оптимизирована под субтильные Live2D-движения. Промпт описывает только движение; 10-30 слов оптимально, на английском.",
    "en": "MiniMax I2V-01-Live is a specialized Image-to-Video model for animating 2D illustrations: anime, manga, digital portraits, concept art. Up to 720P, 6 seconds. The model preserves the original art style and line work, optimized for subtle Live2D-style motion. The prompt describes motion only; 10-30 words is optimal."
  },
  "mystic": {
    "ru": "Mystic 2.5 — проприетарная image-модель Freepik на платформе Pikaso. Текст → изображение до 2K, поддержка референсов типа Style и Character через интерфейс Pikaso. Модель обучена понимать описательные предложения на естественном языке, а не списки тегов. Английский — основной язык; пиши как для фотографа, не как для поисковика.",
    "en": "Mystic 2.5 is Freepik's proprietary image model in the Pikaso platform. Text-to-image up to 2K, with Style and Character reference types via the Pikaso interface. The model is trained to understand descriptive sentences in natural language, not tag lists. English is the primary language; write for a photographer, not for a search engine."
  },
  "nano-banana": {
    "ru": "Nano Banana — общее имя семейства image-моделей Google в Gemini API. Модель понимает естественный язык и полные описательные предложения, поддерживает диалоговое редактирование, Google Search grounding и референсные изображения. Английский — основной язык; tag soup критически снижает качество. Пиши как креативный директор, а не как набор тегов.",
    "en": "Nano Banana is the umbrella name for Google's image model family in the Gemini API. The model understands natural language and full descriptive sentences, supports conversational editing, Google Search grounding, and reference images. English is the primary language; tag soup critically degrades quality. Write like a creative director, not a tag list."
  },
  "nano-banana-2": {
    "ru": "Nano Banana 2 — image-модель Google в Gemini API второго поколения, до 2K с базовым thinking mode и поддержкой до 6 референсов. Модель понимает естественный язык и полные описательные предложения как бриф художника, а не «tag soup». Английский — основной язык; диалоговое редактирование поддерживается.",
    "en": "Nano Banana 2 is Google's second-generation image model in the Gemini API, with up to 2K resolution, basic thinking mode, and support for up to 6 reference images. It reads prompts as a designer brief in natural language — not tag soup. English is the primary language; conversational editing is supported."
  },
  "nano-banana-pro": {
    "ru": "Nano Banana Pro — флагман Google в Gemini 3 Pro Image: 4K, до 14 референсов (6 high fidelity), полный thinking mode и SOTA-рендер текста. Думающая модель: понимает намерение, физику и композицию, читает промпт как бриф креативного директора. Английский — основной язык; JSON-структуры работают отлично.",
    "en": "Nano Banana Pro is Google's flagship in Gemini 3 Pro Image: 4K, up to 14 references (6 high fidelity), full thinking mode, and SOTA text rendering. A thinking model — it understands intent, physics, and composition, reading prompts as a creative-director brief. English is the primary language; JSON structures work great."
  },
  "omni-human": {
    "ru": "OmniHuman 1.5 — специализированная видеомодель ByteDance для анимации людей по схеме Image + Audio → Video. 1024×1024 при 30fps, до 30 секунд через API. Главный драйвер — аудио (lip-sync и body language), текстовый промпт — дополнение для сцены и камеры. Английский для промптов; аудио — на любом языке.",
    "en": "OmniHuman 1.5 is ByteDance's specialized video model for animating people via Image + Audio → Video. 1024×1024 at 30fps, up to 30 seconds via API. The primary driver is audio (lip-sync and body language); the text prompt is a supplement for scene and camera. English for prompts; audio can be in any language."
  },
  "pixverse-6": {
    "ru": "PixVerse V6 — видеомодель PixVerse с нативной генерацией аудио, multi-shot режимом и 20+ cinematic lens controls. Поддерживает T2V и I2V, до 15 секунд при 1080p, негативные промпты и кастомные seed-значения. Лучше всего реагирует на буквальные физические описания, не на метафоры.",
    "en": "PixVerse V6 is a video model from PixVerse with native audio generation, multi-shot mode, and 20+ cinematic lens controls. It supports T2V and I2V, up to 15 seconds at 1080p, negative prompts, and custom seeds. It responds best to literal physical descriptions — not metaphors."
  },
  "qwen-image": {
    "ru": "Qwen Image — image-модель от команды Alibaba Qwen с лидирующим рендерингом текста: коммерческий уровень на английском и китайском, multi-line layouts, параграфы. V2.0 — 7B параметров, нативные 2048×2048, до 1 000 токенов промпта, прямая генерация инфографики, PPT-слайдов, постеров и комиксов с текстовыми пузырями.",
    "en": "Qwen Image is the Alibaba Qwen team's image model with leading text rendering: commercial-grade English and Chinese, multi-line layouts, paragraphs. V2.0 is 7B parameters, native 2048×2048, prompt budget up to 1,000 tokens, and direct generation of infographics, PPT slides, posters, and comics with speech bubbles."
  },
  "recraft-v4": {
    "ru": "Recraft V4 — единственная на рынке AI-модель, генерирующая настоящий редактируемый SVG со структурированными слоями. Точный рендеринг текста, дизайнерский вкус и два режима промптинга: interpretive из 3–6 слов и architectural с полной структурой. Доступно 100+ пресетных стилей через параметр, поддержка негативных промптов, I2I и Figma-плагин.",
    "en": "Recraft V4 is the only AI model that produces true editable SVG with structured layers. Accurate text rendering, real design taste, two prompt modes (interpretive 3–6 words and architectural with full structure), 100+ preset styles via parameter, plus negative prompts and I2I support."
  },
  "reve": {
    "ru": "Reve Image 1.0 — image-модель от Reve AI с 12 миллиардами параметров, нативным 2048×2048 и 4K upscaling. #1 на Artificial Analysis Image Arena (ELO 1167) — выше Midjourney v6.1, Imagen 3, Flux Pro 1.1 и Recraft V3. Сильнейшая верность промпту, 98% точность текста, гиперреалистичные портреты. Полные коммерческие права.",
    "en": "Reve Image 1.0 is an image model from Reve AI with 12 billion parameters, native 2048×2048, and 4K upscaling. It's #1 on Artificial Analysis Image Arena (ELO 1167) — above Midjourney v6.1, Imagen 3, Flux Pro 1.1, and Recraft V3. Strongest prompt fidelity, 98% text accuracy, hyperrealistic portraits. Full commercial rights."
  },
  "runway-act-two": {
    "ru": "Runway Act-Two — это performance transfer модель, а не text-to-video. На вход подаётся driving video с актёрским перформансом и character reference (изображение или видео), модель переносит движение тела, мимику и lip-sync на персонажа. Текстовый промпт здесь играет минимальную роль — качество определяется входными данными.",
    "en": "Runway Act-Two is a performance transfer model, not text-to-video. You feed it a driving video with an actor's performance and a character reference (image or video), and the model transfers body motion, facial expression, and lip-sync onto the character. Text prompts play a minimal role here — quality is set by the inputs."
  },
  "runway-gen4": {
    "ru": "Runway Gen-4 — image-to-video модель от Runway с нативным 720p (апскейл до 4K) и длительностью 5 или 10 секунд. Без входного изображения генерация невозможна — это I2V-only. Промпт описывает ТОЛЬКО движение и камеру, визуал берётся из референса. Негативные промпты и JSON игнорируются.",
    "en": "Runway Gen-4 is an image-to-video model from Runway with native 720p (upscale to 4K) and a fixed duration of 5 or 10 seconds. Generation cannot run without an input image — Gen-4 is I2V-only. The prompt describes ONLY movement and camera; the visual is locked by the reference. Negative prompts and JSON are ignored."
  },
  "runway-gen4.5": {
    "ru": "Runway Gen-4.5 — первая модель Runway с полноценным text-to-video плюс image-to-video в одной архитектуре. Autoregressive-to-Diffusion даёт заметно улучшенную физику воды, ткани и инерции, гибкую длительность от 2 до 10 секунд и уникальный timestamp-синтаксис для последовательных beat'ов внутри одного клипа. Негативные промпты и JSON по-прежнему не работают.",
    "en": "Runway Gen-4.5 is Runway's first model with full text-to-video alongside image-to-video. The Autoregressive-to-Diffusion architecture improves physics (water, fabric, momentum), supports flexible 2–10 second duration, and adds a unique timestamp syntax for sequential beats. Negative prompts and JSON are not supported."
  },
  "seedance": {
    "ru": "Seedance 2.0 — видеомодель от ByteDance (платформа 即梦/Jimeng) с длительностью 4–15 секунд за один запуск и разрешением до 2K. Мощный мультимодальный вход: до 9 изображений, 3 видео и 3 аудио на запрос. 10 типов генерации, timestamp-раскадровка для длинных видео, нативный звуковой контроль. Промпты до 2 000 символов.",
    "en": "Seedance 2.0 is a video model from ByteDance (Jimeng platform) with 4–15 seconds per generation and resolution up to 2K. Powerful multimodal input: up to 9 images, 3 videos, and 3 audio files per request. 10 generation types, timestamp storyboarding for long videos, native voice control. Prompts up to 2,000 characters."
  },
  "seedance-1.0-lite": {
    "ru": "Seedance 1.0 Lite — облегчённая версия Seedance от ByteDance. Фиксированные длительности 5 или 10 секунд, разрешение 480p или 720p, только текст или текст + 1 изображение на вход. Сложные техники из 2.0 (timestamp, @-референсы, voice cloning) тут не работают. Промпты должны быть простыми и прямолинейными, до 1 000 символов.",
    "en": "Seedance 1.0 Lite is the lightweight Seedance variant from ByteDance. Fixed duration of 5 or 10 seconds, resolution 480p or 720p, text-only or text + 1 image input. The advanced techniques from 2.0 (timestamps, @-references, voice cloning) don't work here. Prompts must be simple and direct, up to 1,000 characters."
  },
  "seedance-1.0-pro": {
    "ru": "Seedance 1.0 Pro — полнофункциональная версия первого поколения video-модели ByteDance на платформе 即梦 (Jimeng). Делает 5 или 10 секунд в 720p/1080p, 24fps, принимает текст и одно изображение для Image-to-Video. Сильна в multi-shot с camera switching, но не понимает @-референсы, звук и негативные промпты — это всё появилось в 2.0.",
    "en": "Seedance 1.0 Pro is the full-featured first-generation video model from ByteDance on the 即梦 (Jimeng) platform. It produces 5 or 10 second clips at 720p/1080p, 24fps, and accepts text or one image for Image-to-Video. It is strong on multi-shot with camera switching, but it does not understand @-references, sound, or negative prompts — those all arrived in 2.0."
  },
  "seedance-1.5-pro": {
    "ru": "Seedance 1.5 Pro — промежуточная версия видео-модели ByteDance между поколениями 1.0 и 2.0. Делает 5 или 10 секунд до 1080p, принимает текст и 1–2 изображения. Принесла базовую поддержку negative prompts, простую раскадровку «начало/середина/конец» и расширенный камерный словарь — но без полных @-референсов, звука и точного тайминга по секундам из 2.0.",
    "en": "Seedance 1.5 Pro is ByteDance's intermediate video model between generations 1.0 and 2.0. It produces 5 or 10 second clips up to 1080p and accepts text plus 1–2 images. It introduced basic negative-prompt support, a simple Start / Middle / End storyboard, and an extended camera vocabulary — without the full @-references or sound control of 2.0."
  },
  "seedance-2.0": {
    "ru": "Seedance 2.0 — флагманская видео-модель ByteDance на платформе 即梦 (Jimeng). Делает 4–15 секунд до 2K, принимает до 9 изображений, 3 видео и 3 аудио за запрос. Понимает @-референсы, тайминг-раскадровку по секундам и многослойные TRY CGI-блоки. На syntx.ai стандарт — английский, на нативной платформе лучше работает китайский.",
    "en": "Seedance 2.0 is ByteDance's flagship video model on the 即梦 (Jimeng) platform. It generates 4–15 second clips up to 2K, accepts up to 9 images, 3 videos, and 3 audio inputs per request. It understands @-references, second-by-second storyboarding, and named TRY CGI blocks. On syntx.ai the standard is English; on the native platform Chinese performs better."
  },
  "seedance-new": {
    "ru": "Seedance New — самая свежая итерация видео-модели ByteDance, наследник Seedance 2.0 с экспериментальными улучшениями. Делает 4–15 секунд до 2K, принимает до 9 изображений, 3 видео и 3 аудио. Заметно стабильнее 2.0 на длинных видео и сложных consistency-сценах. Все техники 2.0 работают в полном объёме — это «2.0+», не отдельная архитектура.",
    "en": "Seedance New is the latest iteration of ByteDance's video model, successor to Seedance 2.0 with experimental refinements. It makes 4–15 second clips up to 2K and accepts up to 9 images, 3 videos, and 3 audio inputs. Noticeably more stable than 2.0 on long videos and consistency scenes. All 2.0 techniques apply in full — this is «2.0+», not a separate architecture."
  },
  "seedream": {
    "ru": "Seedream — семейство image-моделей ByteDance: версии 4.0, 4.5, 5 Lite и будущие. Доступны через fal.ai, syntx.ai, YouMind, flux-ai.io. Все версии используют общую архитектуру приоритизации — элементы в начале промпта получают больший вес. Оптимизированы под английский, оптимальная длина — 30–100 слов. Поддерживают негативные промпты на уровне платформы.",
    "en": "Seedream is ByteDance's image model family: versions 4.0, 4.5, 5 Lite, and future releases. Available via fal.ai, syntx.ai, YouMind, and flux-ai.io. Every version uses the same prioritization architecture — elements at the start of the prompt carry more weight. Optimized for English, optimal length is 30–100 words. Negative prompts are supported at the platform level."
  },
  "seedream-4": {
    "ru": "Seedream 4.0 — базовая версия image-модели ByteDance первого поколения семейства. Делает text-to-image до 2K, оптимальная длина промпта 20–80 слов. Доступна через fal.ai, flux-ai.io. Хорошо справляется с простыми сценами и стандартными жанрами, но слабее версий 4.5 и 5 на сложных многоэлементных сценах и пространственных отношениях.",
    "en": "Seedream 4.0 is the baseline image model from ByteDance and the first generation of the family. Text-to-image up to 2K, optimal prompt length 20–80 words. Available via fal.ai and flux-ai.io. Handles simple scenes and standard genres well, but weaker than 4.5 and 5 on complex multi-element scenes and spatial relationships."
  },
  "seedream-4.5": {
    "ru": "Seedream 4.5 — мейнстрим-версия image-модели ByteDance. Делает text-to-image, image-to-image и multi-image blending до 4K. Оптимальная длина промпта 30–100 слов. Доступна через fal.ai, YouMind, flux-ai.io. Принесла читаемый рендеринг текста, пространственное понимание сцен и точное следование сложным инструкциям — главный production-выбор линейки.",
    "en": "Seedream 4.5 is the mainstream version of ByteDance's image model. Text-to-image, image-to-image, and multi-image blending up to 4K. Optimal prompt length is 30–100 words. Available via fal.ai, YouMind, and flux-ai.io. It brought readable in-image text rendering, scene spatial understanding, and precise adherence to complex instructions — the line's main production choice."
  },
  "seedream-5": {
    "ru": "Seedream 5 Lite — самая свежая версия image-модели ByteDance. Делает text-to-image, image-to-image, multi-image blending, inpainting и outpainting до 4K+. Оптимальная длина промпта 30–120 слов. Доступна через fal.ai, syntx.ai. Принесла улучшенный рендеринг текста, заметно лучшую анатомию рук и расширенный диапазон стилей по сравнению с 4.5.",
    "en": "Seedream 5 Lite is the latest version of ByteDance's image model. Text-to-image, image-to-image, multi-image blending, inpainting, and outpainting up to 4K+. Optimal prompt length 30–120 words. Available via fal.ai and syntx.ai. It brought improved text rendering, noticeably better hand anatomy, and an extended style range compared to 4.5."
  },
  "sora": {
    "ru": "Sora — линейка video-моделей от OpenAI с клипами 4-20 секунд и поддержкой консистентных персонажей. Промпт работает как бриф для оператора-постановщика: стиль задаётся первым, дальше идёт субъект, действие, камера, освещение и звук. Английский даёт самые стабильные результаты, особенно для камерной и плёночной терминологии.",
    "en": "Sora is OpenAI's line of video models that produce 4-20 second clips with consistent characters. The prompt works as a brief for a director of photography: style first, then subject, action, camera, lighting, and sound. English gives the most stable results, especially for camera and film-stock vocabulary."
  },
  "sora-2": {
    "ru": "Sora 2 — video-модель от OpenAI с нативным звуком, поддержкой до двух персонажей через Characters API и клипами 4-20 секунд. Промпт работает как бриф для оператора-постановщика: стиль задаётся первым, дальше идёт субъект, действие, камера и звук. Длительность и разрешение задаются только через API-параметры, не текстом.",
    "en": "Sora 2 is OpenAI's video model with native audio, support for up to two characters via the Characters API, and clips of 4-20 seconds. The prompt works like a brief for a director of photography: style first, then subject, action, camera, and sound. Duration and resolution are set only through API parameters, never in the text."
  },
  "veed-fabric": {
    "ru": "Veed Fabric 1.0 — специализированная lip-sync модель, а не генератор видео общего назначения. На вход идёт изображение и аудио (или речевой скрипт для TTS), на выход — анимированный talking head с движениями губ, головы и рук. Поддерживается 30+ языков, до 5 минут через API. Промпт в традиционном смысле не используется.",
    "en": "Veed Fabric 1.0 is a specialized lip-sync model, not a general video generator. The input is an image plus audio (or a TTS speech script), and the output is an animated talking head with lip, head, and hand motion. It supports 30+ languages and up to 5 minutes via API. A traditional text prompt does not apply here."
  },
  "veo": {
    "ru": "Google Veo — линейка video-моделей от DeepMind с клипами 5-8 секунд и базовым разрешением 720p. Промпт работает как описание для режиссёра: субъект, контекст, действие, камера, стиль и освещение. Английский даёт самые стабильные результаты. В семействе разные версии: Veo 1/2 без аудио, Veo 3+ с нативным звуком.",
    "en": "Google Veo is DeepMind's line of video models that produce 5-8 second clips at a base resolution of 720p. The prompt works as a brief for a director: subject, context, action, camera, style, and lighting. English gives the most stable results. The family spans several versions: Veo 1/2 are video-only, Veo 3 and later add native audio."
  },
  "veo-3": {
    "ru": "Veo 3 — первая модель Google DeepMind с нативной генерацией аудио вместе с видео: диалоги, фоновые звуки, музыка, SFX. Клипы ~8 секунд, разрешение 720p, формат 16:9. Промпт обязательно описывает звуковую составляющую, иначе модель додумает её сама и часто неудачно. Английский даёт самые стабильные результаты.",
    "en": "Veo 3 is the first Google DeepMind model to generate audio natively together with video: dialogue, background sounds, music, SFX. Clips are around 8 seconds, resolution 720p, format 16:9. The prompt must describe the audio layer — otherwise the model invents it and often badly. English gives the most stable results."
  },
  "veo-3.1": {
    "ru": "Veo 3.1 — обновлённая видео-модель Google DeepMind с улучшенным следованием промпту, нативным 1080p, вертикальным форматом 9:16 и режимом image-to-video. Наследует генерацию аудио от Veo 3: диалоги, фон, SFX, музыка. Лимит промпта вырос до 2000 символов, длительность — до нескольких минут в расширенном режиме.",
    "en": "Veo 3.1 is Google DeepMind's updated video model with stronger prompt adherence, native 1080p, vertical 9:16 format, and image-to-video. It inherits audio generation from Veo 3: dialogue, ambience, SFX, music. The prompt limit grows to 2000 characters, and clips can run to several minutes in extended mode."
  },
  "wan": {
    "ru": "Wan — открытая T2I-модель от Alibaba, доступная через fal.ai, Replicate и для локального запуска. Принимает промпты на естественном языке с конкретными деталями субъекта, среды, освещения и камеры. Английский даёт самые стабильные результаты, китайский тоже поддерживается. Рекомендуемая длина промпта — 30-100 токенов.",
    "en": "Wan is Alibaba's open-source T2I model, available via fal.ai, Replicate, and for local execution. It accepts natural language prompts with concrete subject, environment, lighting, and camera details. English gives the most stable results, Chinese is also supported. Recommended prompt length is 30-100 tokens."
  },
  "z-image": {
    "ru": "Z-Image — компактная 6B image-модель от Alibaba Tongyi-MAI с открытыми весами под Apache 2.0. Главные фичи — билингвальный рендеринг текста (английский плюс китайский) и встроенный Prompt Enhancer. Доступна в вариантах Base (50 шагов, есть negative prompt) и Turbo (8 шагов, sub-second inference на H800). Запускается на consumer GPU от RTX 3060.",
    "en": "Z-Image is Alibaba Tongyi-MAI's compact 6B image model with open Apache 2.0 weights. Its key features are bilingual text rendering (English plus Chinese) and a built-in Prompt Enhancer. Available in Base (50 steps, negative prompt) and Turbo (8 steps, sub-second inference on H800) variants. Runs on consumer GPUs from RTX 3060 upward."
  }
};
